### ISSUE TITLE
Robust weighting

### ISSUE THREAD

**Issue by keflavich** [urvashirau/ImagingSimulator#5]
Is there any reason "Robust" weighting is a single parameter, rather than allowing robust ⊂ [-2,2] (e.g., per https://casa.nrao.edu/Release4.1.0/doc/UserMan/UserMansu262.html)?  It would be great to be able to play with that parameter too.

**Comment by urvashirau** [comment]
The only reason was simplicity for a first version. 

But, good idea. Check out the TO-DO list in the Docs directory for other ideas that have been asked for. I've added this point as a way to replace the current three weighting choices with a smooth slider that implements the robust weighting scheme.

**Comment by urvashirau** [comment]
Added a slider to smoothly vary the weighting scheme between natural and uniform.

( only 5 years late.... )
