### ISSUE TITLE
Measurement Set as a result

### ISSUE THREAD

**Issue by miguelcarcamov** [urvashirau/ImagingSimulator#6]
Are you guys working on a version on which the simulation gives a Measurement Set as a result?

**Comment by urvashirau** [comment]
Unfortunately, not.  This simulator is intended to be responsive for interactive use (as an introductory teaching tool) and no visibilities are actually constructed or gridded/degridded.  The uv-coverage is generated as the auto-correlation of the array config pattern, and directly multiplied by the FT of the true sky image.
